export const recipes = [
  'Bulgursalaatti',
  'Hernekeitto',
  'Heroinipasta',
  'Hot dog',
  'Itkutofu',
  'Kaalilaatikko',
  'Kanaton curry keitto',
  'Lasagne',
  'Makaronilaatikko',
  'Makkarakastike ja perunaa',
  'Makkarakeitto',
  'Myskikurpitsakeitto',
  'Nachopelti',
  'Nugetit ja Perunamuusi',
  'Nyhtökaura-gnocchivuoka',
  'Nyhtökaurakäristys',
  'Pinaattikeitto',
  'Pitsaperjantai',
  'Quornkiusaus',
  'Quornpihvejä ja kermaperunoita',
  'Sitruunainen hernepasta',
  'Soijarouhebolognese',
  'Tikka masala tofulla',
  'Tofunugetit',
  'Tofunuudelit',
  'Tofupuikot ja hernetahna',
  'Tortilla',
  'Uunipyttipannu',
  'Vegaaninen butter tofu',
  'Vihapullat ja Perunamuusi',
] as const;
